name: Language File Limitation

on:
  pull_request:
    branches:
      - action
      - development
    paths:
      - 'assets/locales/*.json'
      - '!assets/locales/ja.json'

jobs:
  lang_file_limitation:
    name: Language File Limitation
    runs-on: ubuntu-18.04
    steps:
      - name: Transifex
        if: github.actor == 'transifex-integration'
        run: echo you are transifex
      - name: macropygia
        if: github.actor == 'macropygia'
        run: echo you are me!
        run: exit 1
      - name: other
        run: echo you are someone
        run: exit 2
